sudo: required
services:
  - docker

before_install:
  - docker build -t leihuang007/docker-react -f Dockerfile.dev .

script:
  - docker run leihuang007/docker-react npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "eeeeeeeeeee"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"